### DISCUSSION TITLE
Weird identifier problem in TMLanguage syntax highlighting for AS3

### DISCUSSION THREAD

**Discussion by ghost** [airsdk/Adobe-Runtime-Support#3660] [Q&A]
If anyone here is familiar with TMLanguage for Visual Studio Code, I appreciate any help. I've finished a basic TMLanguage grammar for AS3 only, but I'm getting a weird highlighting with the snippet:

```
reviver = JSBridge.toJSFunction("");
```

For some reason, it does not highlight the string literal inside the call. But, if I do

```
reviver = Aaa.aaaaaaaaaaaaaaaaa("");
```

It works. Comparison:

![image](https://github.com/user-attachments/assets/ef615fe3-d34d-47dd-ac81-cba097d249ca)

It does not happen only with string literal; it happens with function expression and anything else.

Highlights of my grammar:

```yaml
# repository: directive (merges directives + statements + expressions)

# Parenthesized
- begin: \(
        end: \)
        name: expression.group
        patterns:
          - include: '#directive'

# String literal
- begin: \@"""
  end: \"""
  name: string.quoted.triple
- begin: \@'''
  end: \'''
  name: string.quoted.triple
- begin: \"""
  end: \"""
  name: string.quoted.triple
  patterns:
    - include: '#stringLiteral'
- begin: \'''
  end: \'''
  name: string.quoted.triple
  patterns:
    - include: '#stringLiteral'
- begin: \@"
  end: \"
  name: string.quoted.double
- begin: \@'
  end: \'
  name: string.quoted.single
- begin: \"
  end: \"
  name: string.quoted.double
  patterns:
    - include: '#stringLiteral'
- begin: \'
  end: \'
  name: string.quoted.single
  patterns:
    - include: '#stringLiteral'

# Dot handling
- match: (\.)\s*({{id}})
  captures:
    1: { name: punctuation }
- begin: (\.)\s*(\<)
  end: \>
  patterns:
    - include: '#directive'
- match: \.\.
  name: keyword.operator
- match: \.
  name: punctuation
```

[Here's the full grammar](https://github.com/whackengine/vscode-extension/blob/master/languages/as3/as3.tmLanguage.yaml)
